name: build

# Controls when the action will run.
on:
  # Triggers the workflow on push
  push:
    branches: [ "feat/**", "fix/**", "develop" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # JOB to run change detection
    changes:
        runs-on: ubuntu-latest
        # Set job outputs to values from filter step
        outputs:
            backend: ${{ steps.filter.outputs.backend }}
            frontend: ${{ steps.filter.outputs.frontend }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  base: ${{github.ref_name}}
                  filters: |
                    backend:
                        - 'backend/**'
                    frontend:
                        - 'frontend/**'

    backend:
      needs: changes
      if: needs.changes.outputs.backend == 'true' 
      runs-on: ubuntu-latest    
      steps:
            - uses: actions/checkout@v3
            - name: do something
              run:  ls

    frontend:
      needs: changes
      if: needs.changes.outputs.frontend == 'true' 
      runs-on: ubuntu-latest    
      steps:
            - uses: actions/checkout@v3
            - name: do something
              run:  ls     

    backend_deploy:
      needs: [backend, frontend]
      runs-on: ubuntu-latest    
      steps:
            - uses: actions/checkout@v3
            - name: do something
              run:  ls

    frontend_deploy:
      needs: [backend,frontend]
      runs-on: ubuntu-latest    
      steps:
            - uses: actions/checkout@v3
            - name: do something
              run:  ls  